version: "2"
services:
  server:
    build:
        dockerfile: Dockerfile
        context: .
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminksemaine.rule=Host(`semaine.adm.ink`)"
      - "traefik.http.routers.adminksemaine.entrypoints=websecure"
      - "traefik.http.routers.adminksemaine.tls.certresolver=myresolver"
      - "traefik.http.services.adminksemaine.loadbalancer.server.port=8080"
networks:
  traefik_default:
    external: true
